name: foram-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.17.1=h8ffe710_1
  - ca-certificates=2021.5.30=h5b45459_0
  - cairo=1.16.0=hba8bd2f_1007
  - certifi=2021.5.30=py39hcbf5309_0
  - cycler=0.10.0=py_2
  - expat=2.2.10=h39d44d4_0
  - ffmpeg=4.3.1=ha925a31_0
  - fontconfig=2.13.1=h1989441_1005
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=h546665d_1
  - gettext=0.19.8.1=h1a89ca6_1005
  - glib=2.66.7=h0e60522_1
  - glib-tools=2.66.7=h0e60522_1
  - graphite2=1.3.13=1000
  - gstreamer=1.18.3=h1613786_0
  - harfbuzz=2.7.4=hc6d2c31_0
  - hdf5=1.10.6=nompi_h5268f04_1114
  - icu=68.1=h0e60522_0
  - intel-openmp=2021.2.0=h57928b3_616
  - jasper=2.0.14=h77af90b_2
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.1=py39h2e07f2f_1
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libclang=11.0.1=default_h5c34c98_1
  - libcurl=7.71.1=h4b64cdc_8
  - libevent=2.1.10=h7a1dbc1_3
  - libffi=3.3=h0e60522_2
  - libflang=5.0.0=h6538335_20180525
  - libglib=2.66.7=h1e62bf3_1
  - libiconv=1.16=he774522_0
  - liblapack=3.9.0=9_mkl
  - liblapacke=3.9.0=9_mkl
  - libllvm11=11.0.1=hab3b255_0
  - libopenblas=0.3.12=pthreads_h1662909_1
  - libopencv=4.5.1=py39h779ee91_1
  - libpng=1.6.37=h1d00b33_2
  - libpq=12.3=h4f54205_3
  - libprotobuf=3.15.8=h7755175_0
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.2.0=hc10be44_0
  - libwebp-base=1.2.0=h8ffe710_2
  - libxcb=1.13=hcd874cb_1003
  - libxml2=2.9.10=hf5bbc77_4
  - llvm-meta=5.0.0=0
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.4.2=py39hcbf5309_0
  - matplotlib-base=3.4.2=py39h581301d_0
  - mkl=2021.2.0=hb70f87d_389
  - msys2-conda-epoch=20160418=1
  - mysql-common=8.0.22=h57928b3_3
  - mysql-libs=8.0.22=hb8c0690_3
  - numpy=1.20.1=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py39hcbf5309_1
  - openmp=5.0.0=vc14_1
  - openssl=1.1.1k=h8ffe710_0
  - pcre=8.44=ha925a31_0
  - pillow=8.1.0=py39h1a9d4f7_2
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pthread-stubs=0.4=hcd874cb_1001
  - py-opencv=4.5.1=py39h832f523_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - pyserial=3.5=pyhd8ed1ab_0
  - python=3.9.1=h7840368_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pywin32=300=py39hb82d6ee_0
  - qt=5.12.9=h5909a2a_4
  - setuptools=49.6.0=py39hcbf5309_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.34.0=h8ffe710_0
  - tbb=2021.2.0=h2d74725_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py39hb82d6ee_1
  - tzdata=2021a=he74cb21_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wheel=0.36.2=pyhd3deb0d_0
  - wincertstore=0.2=py39hcbf5309_1006
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libice=1.0.10=hcd874cb_0
  - xorg-libsm=1.2.3=hcd874cb_1000
  - xorg-libx11=1.6.12=hcd874cb_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-libxext=1.3.4=h301d43c_0
  - xorg-libxrender=0.9.10=h301d43c_1002
  - xorg-renderproto=0.11.1=hcd874cb_1002
  - xorg-xextproto=7.3.0=hcd874cb_1002
  - xorg-xproto=7.0.31=hcd874cb_1007
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.8=h4e2f164_1
